import type { Metadata } from "next";
import { QuickWorkoutGenerator } from "@/components/calculators/quick-workout-generator";
import { RelatedTools } from "@/components/related-tools";

export const metadata: Metadata = {
  title: "Quick Workout Generator",
  description:
    "Pick a goal, your equipment, a focus area, and how much time you have — get a balanced session built from real exercise-selection rules, not a random shuffle.",
  alternates: {
    canonical: "/tools/quick-workout",
  },
  openGraph: {
    title: "Quick Workout Generator | Deload",
    description:
      "Pick a goal, your equipment, a focus area, and how much time you have — get a balanced session built from real exercise-selection rules, not a random shuffle.",
    url: "/tools/quick-workout",
  },
};

const FAQS = [
  {
    question: "How are the exercises actually chosen?",
    answer:
      "By rule, not randomly and not by AI. Every exercise is tagged with a movement pattern (squat, hinge, push, pull, core, carry). Your chosen focus area determines which patterns are required, compound movements are prioritized first, and the number of exercises is sized to roughly fit your time budget under your goal's set/rep/rest scheme. The only randomness is which specific exercise fills a given pattern slot when more than one equipment-appropriate option exists.",
  },
  {
    question: "Should I trust a generated workout instead of seeing a coach?",
    answer:
      "This covers the fundamentals — balanced movement patterns, sensible rep ranges for your goal, a realistic time estimate — but it doesn't know your injury history, technique, or how your last few weeks of training have gone. It's a solid default for a session with no other plan, not a replacement for individualized coaching.",
  },
  {
    question: "What if I don't like one of the exercises it picked?",
    answer:
      "Hit regenerate. It reshuffles which specific exercise fills each movement-pattern slot, so you'll often get a different, equally valid option. There's no substitution picker yet — that's a natural next step for this tool.",
  },
  {
    question: "Does this save my workout or track my history?",
    answer:
      "Not yet — this generates one session at a time with no account required, the same as every other tool on this site right now. Saved workout history is a reasonable future addition once accounts exist.",
  },
  {
    question: "Why does the estimated time sometimes exceed what I asked for?",
    answer:
      "Some goals need long rest periods to actually work — strength training in particular. Rather than quietly cut rest short to hit your exact time budget (which would undercut the goal you picked), the tool tells you honestly when a request needs a bit more time than requested.",
  },
] as const;

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function QuickWorkoutPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      <div className="mx-auto max-w-6xl px-6 py-12 sm:py-16">
        <header className="mx-auto mb-10 flex max-w-2xl flex-col gap-3 text-center">
          <h1 className="text-3xl font-semibold tracking-tight text-foreground sm:text-4xl">
            Quick Workout Generator
          </h1>
          <p className="text-muted-foreground">
            Pick your goal, equipment, focus, and time — get a balanced
            session built from real exercise-selection rules, not a random
            shuffle.
          </p>
        </header>

        <QuickWorkoutGenerator />

        <article className="mx-auto mt-20 flex max-w-2xl flex-col gap-12">
          <section className="flex flex-col gap-3">
            <h2 className="text-xl font-semibold tracking-tight text-foreground">
              What makes this different from a random workout picker
            </h2>
            <p className="text-muted-foreground">
              Every exercise is tagged by the movement pattern it serves —
              squat, hinge, horizontal or vertical push, horizontal or
              vertical pull, core, or carry. Your chosen focus area
              determines which patterns a session needs, and compound,
              multi-joint movements are always prioritized before accessory
              work fills any remaining time. Nothing here is generated by
              a language model — it&rsquo;s the same kind of explainable,
              rule-based logic as the rest of this site.
            </p>
          </section>

          <section className="flex flex-col gap-3">
            <h2 className="text-xl font-semibold tracking-tight text-foreground">
              Frequently asked questions
            </h2>
            <div className="flex flex-col divide-y divide-border">
              {FAQS.map((faq) => (
                <div key={faq.question} className="flex flex-col gap-2 py-5 first:pt-0">
                  <h3 className="font-medium text-foreground">{faq.question}</h3>
                  <p className="text-sm text-muted-foreground">{faq.answer}</p>
                </div>
              ))}
            </div>
          </section>
        </article>
      </div>

      <RelatedTools currentSlug="quick-workout" />
    </>
  );
}
